enum TransactionType {
  DAILY
  INCOME
  EXPENSE
}

type Transaction {
  category: Category @relation
  createdAt: Int!
  date: Date
  month: String!
  name: String
  note: String
  price: Int!
  type: TransactionType!
}

type Category {
  name: String!
  color: String!
}

type Query {
  getCategories: [Category!]!
  getTransactions: [Transaction!]!
  getTransactionsByMonth(month: String!): [Transaction!]!
}
